# Generated by Django 5.0.3 on 2024-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('home', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.CharField(blank=True, max_length=500, null=True)),
                ('projects', models.CharField(blank=True, max_length=500, null=True)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbardaki Başlıkların İsimleri',
            },
        ),
    ]
