# Generated by Django 5.0.3 on 2024-03-15 14:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('first_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('second_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resume', models.CharField(blank=True, max_length=300, null=True)),
                ('projects', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
