# Generated by Django 5.0.3 on 2024-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Main', 'verbose_name_plural': 'Anasayfadaki ilk görünen yazılar'},
        ),
        migrations.AddField(
            model_name='main',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
