# Generated by Django 5.0.3 on 2024-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_main_options_main_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='first_text',
        ),
        migrations.RemoveField(
            model_name='main',
            name='second_text',
        ),
        migrations.AddField(
            model_name='main',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
