# Generated by Django 5.0.3 on 2024-03-15 15:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_main_first_text_remove_main_second_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='first_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
