# Generated by Django 5.0.7 on 2024-07-18 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_resume', models.CharField(blank=True, max_length=300, null=True)),
                ('title_experience', models.CharField(blank=True, max_length=300, null=True)),
                ('date_experience', models.CharField(blank=True, max_length=500, null=True)),
                ('company_experience', models.CharField(blank=True, max_length=700, null=True)),
                ('location_experience', models.CharField(blank=True, max_length=700, null=True)),
                ('description_experience', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_education', models.CharField(blank=True, max_length=300, null=True)),
                ('date_education', models.CharField(blank=True, max_length=500, null=True)),
                ('school_education', models.CharField(blank=True, max_length=700, null=True)),
                ('location_education', models.CharField(blank=True, max_length=700, null=True)),
                ('departman_education', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_education', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title_skills', models.CharField(blank=True, max_length=500, null=True)),
                ('text1_skills', models.TextField(blank=True, null=True)),
                ('text2_skills', models.TextField(blank=True, null=True)),
                ('text3_skills', models.TextField(blank=True, null=True)),
                ('title_languages', models.CharField(blank=True, max_length=500, null=True)),
                ('text1_languages', models.TextField(blank=True, null=True)),
                ('text2_languages', models.TextField(blank=True, null=True)),
                ('text3_languages', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Özgeçmiş',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
