# Generated by Django 5.0.7 on 2024-07-20 07:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_resume_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_experience', models.CharField(blank=True, max_length=500, null=True)),
                ('company_experience', models.CharField(blank=True, max_length=700, null=True)),
                ('location_experience', models.CharField(blank=True, max_length=700, null=True)),
                ('description_experience', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Deneyim',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location_experience',
        ),
    ]
