# Generated by Django 5.0.7 on 2024-07-20 07:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_experience_remove_resume_company_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_education', models.CharField(blank=True, max_length=500, null=True)),
                ('school_education', models.CharField(blank=True, max_length=700, null=True)),
                ('location_education', models.CharField(blank=True, max_length=700, null=True)),
                ('departman_education', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_education', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Eğitim',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='departman_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='school_education',
        ),
    ]
