# Generated by Django 5.0.7 on 2024-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_education_remove_resume_date_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1_skills', models.TextField(blank=True, null=True)),
                ('text2_skills', models.TextField(blank=True, null=True)),
                ('text3_skills', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Yetenekler',
            },
        ),
    ]
