# Generated by Django 5.0.7 on 2024-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1_languages', models.TextField(blank=True, null=True)),
                ('text2_languages', models.TextField(blank=True, null=True)),
                ('text3_languages', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text1_languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text1_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text2_languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text2_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text3_languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='text3_skills',
        ),
    ]
