# Generated by Django 5.0.7 on 2024-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_language_remove_resume_text1_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Proje linki'),
        ),
    ]
