# Generated by Django 5.0.7 on 2024-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_contact_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ContactTitle',
                'verbose_name_plural': 'İletişim sayfasındaki yazı',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
