# Generated by Django 5.0.7 on 2024-07-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_contacttitle_remove_contact_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTitle',
        ),
    ]
