# Generated by Django 5.0.7 on 2024-07-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Privacy metni'},
        ),
    ]
