# Generated by Django 5.0.7 on 2024-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_policy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ContactName',
                'verbose_name_plural': 'İletişim sayfasının başındaki yazı',
            },
        ),
    ]
